### ISSUE TITLE
Activity_main2

### ISSUE THREAD

**Issue by Shortowsky** [TRG-Development/ArmA3-ATragMX#1]
RC Button can't be renamed, as other Buttons linked to it would go crazy. Still haven't found out how to renamed everything.

**Comment by Sceinox** [comment]
Can you please give more information.

I'll trying to fix this issue in the evening (~10pm)

**Comment by Shortowsky** [comment]
Most buttons in the Layout are linked in position relative to the first one i created: RC
I tried renaming it, but then the buttons go crazy because their orientation to "RC" is gone.
I don't know how to tell the buttons that they should orientate relative to the button named "Button_RC" and not "RC"

**Comment by Sceinox** [comment]
Okay, I'll take a look at it in the evening
