### ISSUE TITLE
Note Screen

### ISSUE THREAD

**Issue by Schmitt-Florian** [TRG-Development/ArmA3-ATragMX#22]
Please design a simple GUI to show Notes from Guns (with cancel, edit, save buttons)

**Comment by Shortowsky** [comment]
WIP

**Comment by Schmitt-Florian** [comment]
can you add some kind of textview at the top to display the weaponname please?

**Comment by Shortowsky** [comment]
will do

**Comment by Schmitt-Florian** [comment]
thanks

**Comment by Shortowsky** [comment]
done

**Comment by Schmitt-Florian** [comment]
finished
