### ISSUE TITLE
Change presentation of Atmpshr-Section in Main Activity

### ISSUE THREAD

**Issue by Schmitt-Florian** [TRG-Development/ArmA3-ATragMX#25]
Change presentation of Atmpshr-Section in Main Activity, to depend on which calculation method was choosen in Atmpshr- Activity (TBH or AT)

**Comment by Shortowsky** [comment]
can you make a picture pls (Paint or else) i dont quite understand.

**Comment by Schmitt-Florian** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/22458829/23095515/47ecd25a-f60b-11e6-84d8-4de6d0c1d535.png)

something like this would totally do the job

**Comment by Shortowsky** [comment]
done

**Comment by Shortowsky** [comment]
Is already pushed ?!? pls check again.

**Comment by Schmitt-Florian** [comment]
https://github.com/TRG-Development/ArmA3-ATragMX/commits/master

"lastest commit 4 days ago"

**Comment by Schmitt-Florian** [comment]
Now implemented in f59fc2b29175c1a28989271aa37a80ad83a7139f
