### ISSUE TITLE
Atmsphr Screen

### ISSUE THREAD

**Issue by Sceinox** [TRG-Development/ArmA3-ATragMX#4]
ToDo

**Comment by Schmitt-Florian** [comment]
Please implement the methodswitch to TBH as soon as possible, because the calculator can't be continued due missing option to insert the specific values of BarometricPressure and Humidity

**Comment by Schmitt-Florian** [comment]
@Shortowsky Thanks for your commitment, done it in 7a585d3a330911ac584e25a1a622b4c788962d9d myself untli waiting a month
