### ISSUE TITLE
TR Screen

### ISSUE THREAD

**Issue by Sceinox** [TRG-Development/ArmA3-ATragMX#7]
ToDo

**Comment by Schmitt-Florian** [comment]
@Shortowsky Can you tell me, what the "Applay Value"-Button is for and what it should do?

**Comment by Shortowsky** [comment]
To adopt the calculated value into the main screen for further calculating

**Comment by Schmitt-Florian** [comment]
Can't continue until @Shortowsky solved #24

**Comment by Schmitt-Florian** [comment]
Done
