### ISSUE TITLE
Gunlist Screen

### ISSUE THREAD

**Issue by Sceinox** [TRG-Development/ArmA3-ATragMX#9]
ToDo

**Comment by Schmitt-Florian** [comment]
designend GUI, but Buttons don't work

**Comment by Sceinox** [comment]
what do I need to do?

**Comment by Schmitt-Florian** [comment]
fix the Buttons?

**Comment by Sceinox** [comment]
Yes, no, maybe, i don't know. Can you repeat the question?

**Comment by Sceinox** [comment]
what is the problem with the buttons?

Which Button do you mean?

On which activity are the non-working buttons?

pleave give more information about problems.

"does not work is not a good bug report"

see: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines
 fore example

**Comment by Schmitt-Florian** [comment]
Error occurs when clicking on Buttons (all) in the gunlist-screen. -> Programm crashes with following exception:
java.lang.IllegalStateException: Could not find method onAddClick(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.support.v7.widget.AppCompatButton with id 'Button_AddGun'

**Comment by Sceinox** [comment]
fixed now

**Comment by Schmitt-Florian** [comment]
can't continue until #22 is finished

**Comment by Schmitt-Florian** [comment]
finished
